language: php

dist: trusty
sudo: required

matrix:
  include:
    - php: '7.1'
      services: mariadb
      addons:
        mariadb: '10.0'
      env:
        - DB_TYPE=mariadb DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.1'
      services: mysql
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.1'
      services: mysql
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
      before_install:
        - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
        - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
        - sudo systemctl restart mysql
        - sudo mysql_upgrade
        - mysql --version
    - php: '7.1'
      services: postgresql
      env:
        - DB_TYPE=pgsql DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=5432 DB_USERNAME=postgres DB_PASSWORD=root
    - php: '7.2'
      services: mariadb
      addons:
        mariadb: '10.0'
      env:
        - DB_TYPE=mariadb DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.2'
      services: mysql
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.2'
      services: mysql
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
      before_install:
        - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
        - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
        - sudo systemctl restart mysql
        - sudo mysql_upgrade
        - mysql --version
    - php: '7.2'
      services: postgresql
      env:
        - DB_TYPE=pgsql DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=5432 DB_USERNAME=postgres DB_PASSWORD=root
    - php: '7.3'
      services: mariadb
      addons:
        mariadb: '10.0'
      env:
        - DB_TYPE=mariadb DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.3'
      services: mysql
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.3'
      services: mysql
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
      before_install:
        - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
        - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
        - sudo systemctl restart mysql
        - sudo mysql_upgrade
        - mysql --version
    - php: '7.3'
      services: postgresql
      env:
        - DB_TYPE=pgsql DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=5432 DB_USERNAME=postgres DB_PASSWORD=root
    - php: '7.4snapshot'
      services: mariadb
      addons:
        mariadb: '10.0'
      env:
        - DB_TYPE=mariadb DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.4snapshot'
      services: mysql
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
    - php: '7.4snapshot'
      services: mysql
      env:
        - DB_TYPE=mysql DB_NAME=yii2_enum DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=
      before_install:
        - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
        - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
        - sudo systemctl restart mysql
        - sudo mysql_upgrade
        - mysql --version
    - php: '7.4snapshot'
      services: postgresql
      env:
        - DB_TYPE=pgsql DB_NAME=yii2_enum DB_HOST=localhost DB_PORT=5432 DB_USERNAME=postgres DB_PASSWORD=root

before_install:
  - sh -c "if [ '$DB_TYPE' = 'pgsql' ]; then psql -c 'CREATE DATABASE yii2_enum;' -U postgres; fi"
  - sh -c "if [ '$DB_TYPE' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS yii2_enum;'; fi"
  - sh -c "if [ '$DB_TYPE' = 'mariadb' ]; then mysql -e 'CREATE DATABASE yii2_enum;'; fi"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - travis_retry composer build

after_success:
  - bash <(curl -s https://codecov.io/bash)
